### ISSUE TITLE
Suggestion: Remove the requirement for the Stripe-PHP package

### ISSUE THREAD

**Issue by NoelDavies** [JacobBennett/StripeTestToken#3]
If people just want the cards numbers defined as readable constants this would be handy, but a developer might be using something other than the official stripe-php lib for this, eg, they might be using the JS implementation and want your package for use in a end-to-end test?

**Comment by JacobBennett** [comment]
Could use some clarification for your use case on this. 

You are proposing using this library as a way to JUST get the card numbers, is that correct? Instead of actually returning a token, you would have it return the card number.

if you were using the JS implementation, wouldn't you also be using the stripe-php lib on your server side to actually do the charges?

**Comment by JacobBennett** [comment]
I think I might have a better understanding now actually, so if I'm in an end to end test, and I just want to generate the cardNumber to fill in the form with, then you can't do this with the package here correct?

So I am of a few different minds on this. You could call something like,

`StripeTestToken::validVisa($cardNumberOnly = true)`

or I could make another library just for referencing the card numbers that THIS package pulls in. That would allow you to do something like:

`StripeCardNumber::validVisa()` 

which would return the card number only. This StripeTestToken package would then just act as a decorator on top of that class to wrap the call to the card number in a request to get a token from Stripe. Hmmm... ideas? Thoughts?
